### ISSUE TITLE
Item Image Placeholder

### ISSUE THREAD

**Issue by ljwhite** [ajtran303/monster_shop_2005#112]
If an item is added/modified without an image, there is supposed to be a placeholder. I'm not sure what this means or how we should implement it. For discussion prior to project submission.

**Comment by ajtran303** [comment]
How about just making the Item model default image url the placeholder we use in the ItemFactory?

```ruby
# factories.rb
placeholder_image = "https://www.webfx.com/blog/images/cdn.designinstruct.com/files/582-how-to-image-placeholders/generic-image-placeholder.png"
```

**Comment by ajtran303** [comment]
https://blog.arkency.com/how-to-add-a-default-value-to-an-existing-column-in-a-rails-migration/

I can try working on this

**Comment by ljwhite** [comment]
That seems like a great idea. Honestly, I just totally forgot about it while completing the user story.

**Comment by ajtran303** [comment]
#118 closes this issue
