### ISSUE TITLE
Final edits before merging login_logout branch to master

### ISSUE THREAD

**Issue by rrabinovitch** [ajtran303/monster_shop_2005#37]
Once the Navigation user stories are complete,
• the route for logging out will be updated to be accessed via a logout link in the navbar rather than visiting a logout path
• confirm that login button does not appear when a user is logged in already and that a logout button is displayed instead
• confirm no conflict re: home page/root route between this branch's code and navbar branch's code
• refactor SessionsController to DRY up code

**Comment by ajtran303** [comment]
The Navigation stories are complete on this new branch [navigation](https://github.com/ajtran303/monster_shop_2005/tree/navigation)

It is not merged to master yet either.
Heads up: in this branch, the `"/"` path routes to `ApplicationController`, so you know where to look first.
