### ISSUE TITLE
User Story 19, User Profile Show Page

### ISSUE THREAD

**Issue by rrabinovitch** [ajtran303/monster_shop_2005#38]
As a registered user
When I visit my profile page
Then I see all of my profile data on the page except my password
And I see a link to edit my profile data

**Comment by ajtran303** [comment]
We should talk -- it looks like these features will utilize the UsersController that I wrote.
I'm currently refactoring it because I'm about to use it in my stories about User Orders - let's make sure we're on the same codebase.

**Comment by rrabinovitch** [comment]
@ajtran303 When will you be able to have a branch with that refactored code pushed to github and ready for me to merge into this `user_profile_show_page` branch so I can use that code to move forward with this user story?

**Comment by ajtran303** [comment]
I just sent the [PR for review](https://github.com/ajtran303/monster_shop_2005/pull/47)
